export * as system from './system/calls'
export * as subspace from './subspace/calls'
export * as balances from './balances/calls'
export * as domains from './domains/calls'
export * as rewards from './rewards/calls'
