query AccountTransferSenderTotalCount(
  $limit: Int!
  $offset: Int
  $orderBy: [leaderboard_account_transfer_sender_total_counts_order_by!]!
  $where: leaderboard_account_transfer_sender_total_counts_bool_exp
) {
  leaderboard_account_transfer_sender_total_counts_aggregate(where: $where) {
    aggregate {
      count
    }
  }
  leaderboard_account_transfer_sender_total_counts(
    limit: $limit
    offset: $offset
    order_by: $orderBy
    where: $where
  ) {
    id
    rank
    value
    lastContributionAt: last_contribution_at
    createdAt: created_at
    updatedAt: updated_at
  }
}

query AccountTransferSenderTotalValue(
  $limit: Int!
  $offset: Int
  $orderBy: [leaderboard_account_transfer_sender_total_values_order_by!]!
  $where: leaderboard_account_transfer_sender_total_values_bool_exp
) {
  leaderboard_account_transfer_sender_total_values_aggregate(where: $where) {
    aggregate {
      count
    }
  }
  leaderboard_account_transfer_sender_total_values(
    limit: $limit
    offset: $offset
    order_by: $orderBy
    where: $where
  ) {
    id
    rank
    value
    lastContributionAt: last_contribution_at
    createdAt: created_at
    updatedAt: updated_at
  }
}

query AccountTransferReceiverTotalCount(
  $limit: Int!
  $offset: Int
  $orderBy: [leaderboard_account_transfer_receiver_total_counts_order_by!]!
  $where: leaderboard_account_transfer_receiver_total_counts_bool_exp
) {
  leaderboard_account_transfer_receiver_total_counts_aggregate(order_by: $orderBy, where: $where) {
    aggregate {
      count
    }
  }
  leaderboard_account_transfer_receiver_total_counts(
    limit: $limit
    offset: $offset
    order_by: $orderBy
    where: $where
  ) {
    id
    rank
    value
    lastContributionAt: last_contribution_at
    createdAt: created_at
    updatedAt: updated_at
  }
}

query AccountTransferReceiverTotalValue(
  $limit: Int!
  $offset: Int
  $orderBy: [leaderboard_account_transfer_receiver_total_values_order_by!]!
  $where: leaderboard_account_transfer_receiver_total_values_bool_exp
) {
  leaderboard_account_transfer_receiver_total_values_aggregate(order_by: $orderBy, where: $where) {
    aggregate {
      count
    }
  }
  leaderboard_account_transfer_receiver_total_values(
    limit: $limit
    offset: $offset
    order_by: $orderBy
    where: $where
  ) {
    id
    rank
    value
    lastContributionAt: last_contribution_at
    createdAt: created_at
    updatedAt: updated_at
  }
}

query AccountRemarkCount(
  $limit: Int!
  $offset: Int
  $orderBy: [leaderboard_account_remark_counts_order_by!]!
  $where: leaderboard_account_remark_counts_bool_exp
) {
  leaderboard_account_remark_counts_aggregate(where: $where) {
    aggregate {
      count
    }
  }
  leaderboard_account_remark_counts(
    limit: $limit
    offset: $offset
    order_by: $orderBy
    where: $where
  ) {
    id
    rank
    value
    lastContributionAt: last_contribution_at
    createdAt: created_at
    updatedAt: updated_at
  }
}

query AccountExtrinsicTotalCount(
  $limit: Int!
  $offset: Int
  $orderBy: [leaderboard_account_extrinsic_total_counts_order_by!]!
  $where: leaderboard_account_extrinsic_total_counts_bool_exp
) {
  leaderboard_account_extrinsic_total_counts_aggregate(where: $where) {
    aggregate {
      count
    }
  }
  leaderboard_account_extrinsic_total_counts(
    limit: $limit
    offset: $offset
    order_by: $orderBy
    where: $where
  ) {
    id
    rank
    value
    lastContributionAt: last_contribution_at
    createdAt: created_at
    updatedAt: updated_at
  }
}

query AccountExtrinsicSuccessTotalCount(
  $limit: Int!
  $offset: Int
  $orderBy: [leaderboard_account_extrinsic_success_total_counts_order_by!]!
  $where: leaderboard_account_extrinsic_success_total_counts_bool_exp
) {
  leaderboard_account_extrinsic_success_total_counts_aggregate(order_by: $orderBy, where: $where) {
    aggregate {
      count
    }
  }
  leaderboard_account_extrinsic_success_total_counts(
    limit: $limit
    offset: $offset
    order_by: $orderBy
    where: $where
  ) {
    id
    rank
    value
    lastContributionAt: last_contribution_at
    createdAt: created_at
    updatedAt: updated_at
  }
}

query AccountExtrinsicFailedTotalCount(
  $limit: Int!
  $offset: Int
  $orderBy: [leaderboard_account_extrinsic_failed_total_counts_order_by!]!
  $where: leaderboard_account_extrinsic_failed_total_counts_bool_exp
) {
  leaderboard_account_extrinsic_failed_total_counts_aggregate(where: $where) {
    aggregate {
      count
    }
  }
  leaderboard_account_extrinsic_failed_total_counts(
    limit: $limit
    offset: $offset
    order_by: $orderBy
    where: $where
  ) {
    id
    rank
    value
    lastContributionAt: last_contribution_at
    createdAt: created_at
    updatedAt: updated_at
  }
}

query AccountTransactionFeePaidTotalValue(
  $limit: Int!
  $offset: Int
  $orderBy: [leaderboard_account_transaction_fee_paid_total_values_order_by!]!
  $where: leaderboard_account_transaction_fee_paid_total_values_bool_exp
) {
  leaderboard_account_transaction_fee_paid_total_values_aggregate(
    order_by: $orderBy
    where: $where
  ) {
    aggregate {
      count
    }
  }
  leaderboard_account_transaction_fee_paid_total_values(
    limit: $limit
    offset: $offset
    order_by: $orderBy
    where: $where
  ) {
    id
    rank
    value
    lastContributionAt: last_contribution_at
    createdAt: created_at
    updatedAt: updated_at
  }
}

query FarmerVoteTotalCount(
  $limit: Int!
  $offset: Int
  $orderBy: [leaderboard_farmer_vote_total_counts_order_by!]!
  $where: leaderboard_farmer_vote_total_counts_bool_exp
) {
  leaderboard_farmer_vote_total_counts_aggregate(where: $where) {
    aggregate {
      count
    }
  }
  leaderboard_farmer_vote_total_counts(
    limit: $limit
    offset: $offset
    order_by: $orderBy
    where: $where
  ) {
    id
    rank
    value
    lastContributionAt: last_contribution_at
    createdAt: created_at
    updatedAt: updated_at
  }
}

query FarmerVoteTotalValue(
  $limit: Int!
  $offset: Int
  $orderBy: [leaderboard_farmer_vote_total_values_order_by!]!
  $where: leaderboard_farmer_vote_total_values_bool_exp
) {
  leaderboard_farmer_vote_total_values_aggregate(where: $where) {
    aggregate {
      count
    }
  }
  leaderboard_farmer_vote_total_values(
    limit: $limit
    offset: $offset
    order_by: $orderBy
    where: $where
  ) {
    id
    rank
    value
    lastContributionAt: last_contribution_at
    createdAt: created_at
    updatedAt: updated_at
  }
}

query FarmerBlockTotalCount(
  $limit: Int!
  $offset: Int
  $orderBy: [leaderboard_farmer_block_total_counts_order_by!]!
  $where: leaderboard_farmer_block_total_counts_bool_exp
) {
  leaderboard_farmer_block_total_counts_aggregate(where: $where) {
    aggregate {
      count
    }
  }
  leaderboard_farmer_block_total_counts(
    limit: $limit
    offset: $offset
    order_by: $orderBy
    where: $where
  ) {
    id
    rank
    value
    lastContributionAt: last_contribution_at
    createdAt: created_at
    updatedAt: updated_at
  }
}

query FarmerBlockTotalValue(
  $limit: Int!
  $offset: Int
  $orderBy: [leaderboard_farmer_block_total_values_order_by!]!
  $where: leaderboard_farmer_block_total_values_bool_exp
) {
  leaderboard_farmer_block_total_values_aggregate(where: $where) {
    aggregate {
      count
    }
  }
  leaderboard_farmer_block_total_values(
    limit: $limit
    offset: $offset
    order_by: $orderBy
    where: $where
  ) {
    id
    rank
    value
    lastContributionAt: last_contribution_at
    createdAt: created_at
    updatedAt: updated_at
  }
}

query OperatorTotalRewardsCollected(
  $limit: Int!
  $offset: Int
  $orderBy: [leaderboard_operator_total_rewards_collecteds_order_by!]!
  $where: leaderboard_operator_total_rewards_collecteds_bool_exp
) {
  leaderboard_operator_total_rewards_collecteds_aggregate(where: $where) {
    aggregate {
      count
    }
  }
  leaderboard_operator_total_rewards_collecteds(
    limit: $limit
    offset: $offset
    order_by: $orderBy
    where: $where
  ) {
    id
    rank
    value
    lastContributionAt: last_contribution_at
    createdAt: created_at
    updatedAt: updated_at
  }
}

query OperatorTotalTaxCollected(
  $limit: Int!
  $offset: Int
  $orderBy: [leaderboard_operator_total_tax_collecteds_order_by!]!
  $where: leaderboard_operator_total_tax_collecteds_bool_exp
) {
  leaderboard_operator_total_tax_collecteds_aggregate(where: $where) {
    aggregate {
      count
    }
  }
  leaderboard_operator_total_tax_collecteds(
    limit: $limit
    offset: $offset
    order_by: $orderBy
    where: $where
  ) {
    id
    rank
    value
    lastContributionAt: last_contribution_at
    createdAt: created_at
    updatedAt: updated_at
  }
}

query OperatorBundleTotalCount(
  $limit: Int!
  $offset: Int
  $orderBy: [leaderboard_operator_bundle_total_counts_order_by!]!
  $where: leaderboard_operator_bundle_total_counts_bool_exp
) {
  leaderboard_operator_bundle_total_counts_aggregate(where: $where) {
    aggregate {
      count
    }
  }
  leaderboard_operator_bundle_total_counts(
    limit: $limit
    offset: $offset
    order_by: $orderBy
    where: $where
  ) {
    id
    rank
    value
    lastContributionAt: last_contribution_at
    createdAt: created_at
    updatedAt: updated_at
  }
}

query OperatorDepositsTotalCount(
  $limit: Int!
  $offset: Int
  $orderBy: [leaderboard_operator_deposits_total_counts_order_by!]!
  $where: leaderboard_operator_deposits_total_counts_bool_exp
) {
  leaderboard_operator_deposits_total_counts_aggregate(where: $where) {
    aggregate {
      count
    }
  }
  leaderboard_operator_deposits_total_counts(
    limit: $limit
    offset: $offset
    order_by: $orderBy
    where: $where
  ) {
    id
    rank
    value
    lastContributionAt: last_contribution_at
    createdAt: created_at
    updatedAt: updated_at
  }
}

query OperatorDepositsTotalValue(
  $limit: Int!
  $offset: Int
  $orderBy: [leaderboard_operator_deposits_total_values_order_by!]!
  $where: leaderboard_operator_deposits_total_values_bool_exp
) {
  leaderboard_operator_deposits_total_values_aggregate(where: $where) {
    aggregate {
      count
    }
  }
  leaderboard_operator_deposits_total_values(
    limit: $limit
    offset: $offset
    order_by: $orderBy
    where: $where
  ) {
    id
    rank
    value
    lastContributionAt: last_contribution_at
    createdAt: created_at
    updatedAt: updated_at
  }
}

query OperatorWithdrawalsTotalCount(
  $limit: Int!
  $offset: Int
  $orderBy: [leaderboard_operator_withdrawals_total_counts_order_by!]!
  $where: leaderboard_operator_withdrawals_total_counts_bool_exp
) {
  leaderboard_operator_withdrawals_total_counts_aggregate(where: $where) {
    aggregate {
      count
    }
  }
  leaderboard_operator_withdrawals_total_counts(
    limit: $limit
    offset: $offset
    order_by: $orderBy
    where: $where
  ) {
    id
    rank
    value
    lastContributionAt: last_contribution_at
    createdAt: created_at
    updatedAt: updated_at
  }
}

query NominatorDepositsTotalCount(
  $limit: Int!
  $offset: Int
  $orderBy: [leaderboard_nominator_deposits_total_counts_order_by!]!
  $where: leaderboard_nominator_deposits_total_counts_bool_exp
) {
  leaderboard_nominator_deposits_total_counts_aggregate(where: $where) {
    aggregate {
      count
    }
  }
  leaderboard_nominator_deposits_total_counts(
    limit: $limit
    offset: $offset
    order_by: $orderBy
    where: $where
  ) {
    id
    rank
    value
    lastContributionAt: last_contribution_at
    createdAt: created_at
    updatedAt: updated_at
  }
}

query NominatorDepositsTotalValue(
  $limit: Int!
  $offset: Int
  $orderBy: [leaderboard_nominator_deposits_total_values_order_by!]!
  $where: leaderboard_nominator_deposits_total_values_bool_exp
) {
  leaderboard_nominator_deposits_total_values_aggregate(where: $where) {
    aggregate {
      count
    }
  }
  leaderboard_nominator_deposits_total_values(
    limit: $limit
    offset: $offset
    order_by: $orderBy
    where: $where
  ) {
    id
    rank
    value
    lastContributionAt: last_contribution_at
    createdAt: created_at
    updatedAt: updated_at
  }
}

query NominatorWithdrawalsTotalCount(
  $limit: Int!
  $offset: Int
  $orderBy: [leaderboard_nominator_withdrawals_total_counts_order_by!]!
  $where: leaderboard_nominator_withdrawals_total_counts_bool_exp
) {
  leaderboard_nominator_withdrawals_total_counts_aggregate(where: $where) {
    aggregate {
      count
    }
  }
  leaderboard_nominator_withdrawals_total_counts(
    limit: $limit
    offset: $offset
    order_by: $orderBy
    where: $where
  ) {
    id
    rank
    value
    lastContributionAt: last_contribution_at
    createdAt: created_at
    updatedAt: updated_at
  }
}

query FarmerVoteAndBlockTotalCount(
  $limit: Int!
  $offset: Int
  $orderBy: [leaderboard_farmer_vote_and_block_total_counts_order_by!]!
  $where: leaderboard_farmer_vote_and_block_total_counts_bool_exp
) {
  leaderboard_farmer_vote_and_block_total_counts_aggregate(where: $where) {
    aggregate {
      count
    }
  }
  leaderboard_farmer_vote_and_block_total_counts(
    limit: $limit
    offset: $offset
    order_by: $orderBy
    where: $where
  ) {
    id
    rank
    value
    lastContributionAt: last_contribution_at
    createdAt: created_at
    updatedAt: updated_at
  }
}

query FarmerVoteAndBlockTotalValue(
  $limit: Int!
  $offset: Int
  $orderBy: [leaderboard_farmer_vote_and_block_total_values_order_by!]!
  $where: leaderboard_farmer_vote_and_block_total_values_bool_exp
) {
  leaderboard_farmer_vote_and_block_total_values_aggregate(where: $where) {
    aggregate {
      count
    }
  }
  leaderboard_farmer_vote_and_block_total_values(
    limit: $limit
    offset: $offset
    order_by: $orderBy
    where: $where
  ) {
    id
    rank
    value
    lastContributionAt: last_contribution_at
    createdAt: created_at
    updatedAt: updated_at
  }
}
