

  # Account Worker
  services:
    account-worker:
      profiles: [indexers]
      build:
        context: ./indexers
        dockerfile: workers/account-worker/Dockerfile
      depends_on:
        pgcat:
          condition: service_healthy
        postgres:
          condition: service_healthy
        redis:
          condition: service_healthy
        node:
          condition: service_healthy
      restart: unless-stopped
      environment:
          AUTONOMYS_NODE_URL: ${RPC_URLS}
          DB_HOST: ${DB_HOST}
          DB_PORT: ${DB_PORT}
          DB_USER: ${DB_USER}
          DB_PASSWORD: ${DB_PASSWORD}
          DB_NAME: ${DB_DATABASE}
          REDIS_URL: "redis://${REDIS_SERVICE_HOST:-redis}:${REDIS_SERVICE_PORT:-6379}"
          ACCOUNT_PROCESSING_QUEUE_NAME: "${ACCOUNT_PROCESSING_QUEUE_NAME:-account_updates_queue}"
          PROCESSING_DEPTH: "${PROCESSING_DEPTH:-10}"
          CHAIN_HEAD_POLL_INTERVAL_MS: "${CHAIN_HEAD_POLL_INTERVAL_MS:-5000}"
          QUEUE_PROCESSING_INTERVAL_MS: "${QUEUE_PROCESSING_INTERVAL_MS:-5000}"
          BATCH_SIZE: "${BATCH_SIZE:-500}"
          # Database Pool Configuration
          DB_POOL_MAX: "${DB_POOL_MAX:-20}"
          DB_POOL_MIN: "${DB_POOL_MIN:-5}"
          DB_CONNECTION_TIMEOUT_MS: "${DB_CONNECTION_TIMEOUT_MS:-3000}"
          DB_QUERY_TIMEOUT_MS: "${DB_QUERY_TIMEOUT_MS:-10000}"
          DB_STATEMENT_TIMEOUT_MS: "${DB_STATEMENT_TIMEOUT_MS:-10000}"
          DB_IDLE_TIMEOUT_MS: "${DB_IDLE_TIMEOUT_MS:-30000}"
          # Database Update Processing
          DB_UPDATE_CHUNK_SIZE: "${DB_UPDATE_CHUNK_SIZE:-25}"
          DB_UPDATE_CHUNK_DELAY_MS: "${DB_UPDATE_CHUNK_DELAY_MS:-100}"
          # Health Check Configuration
          DB_HEALTH_CHECK_INTERVAL_MS: "${DB_HEALTH_CHECK_INTERVAL_MS:-10000}"
      healthcheck:
        test: ["CMD", "node", "-e", "process.exit(0)"]
        interval: 30s
        timeout: 10s
        start_period: 5s
        retries: 3