query TransferHistory(
  $limit: Int!
  $offset: Int
  $orderBy: [consensus_transfers_order_by!]!
  $where: consensus_transfers_bool_exp
) {
  consensus_transfers_aggregate(where: $where) {
    aggregate {
      count
    }
  }
  consensus_transfers(limit: $limit, offset: $offset, order_by: $orderBy, where: $where) {
    block_hash
    block_height
    event_id
    extrinsic_id
    fee
    from
    from_chain
    id
    success
    timestamp
    to
    to_chain
    value
  }
}
