export const emptyOperator = {
  id: "0",
  operatorId: 0,
  signingKey: "0x",
  operatorOwner: "st",
  minimumNominatorStake: BigInt(0),
  nominationTax: 0,
  taxCollected: BigInt(0),
  pendingTotalStake: BigInt(0),
  pendingStorageFeeDeposit: BigInt(0),
  currentTotalStake: BigInt(0),
  currentStorageFeeDeposit: BigInt(0),
  currentEpochRewards: BigInt(0),
  currentTotalShares: BigInt(0),
  deposits: [],
  nominators: [],
  withdrawals: [],
  operatorRewards: [],
  operatorFees: [],
  status: JSON.stringify({}),
  depositsCount: 0,
  nominatorsCount: 0,
  withdrawalsCount: 0,
  bundleCount: 0,
  lastBundleAt: 0,
  updatedAt: 0,
};

export const emptyOperatorRewardEvent = {
  id: "0",
  timestamp: new Date(0),
  blockNumber: 0,
  extrinsicHash: "0x",
  amount: BigInt(0),
};
