module.exports = class Data1723158746926 {
    name = 'Data1723158746926'

    async up(db) {
        await db.query(`CREATE TABLE "account_transfer_sender_total_count" ("id" character varying NOT NULL, "sort_id" integer NOT NULL, "account_id" text NOT NULL, "value" integer NOT NULL, "last_contribution_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_e552546f78849e8eab40a2abe00" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_5a702db2bccbcac5bd5746e383" ON "account_transfer_sender_total_count" ("sort_id") `)
        await db.query(`CREATE INDEX "IDX_931cdd001f2cc8877feb2c80d3" ON "account_transfer_sender_total_count" ("account_id") `)
        await db.query(`CREATE TABLE "account_transfer_sender_total_value" ("id" character varying NOT NULL, "sort_id" integer NOT NULL, "account_id" text NOT NULL, "value" numeric NOT NULL, "last_contribution_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_f9289e86e0a038c9a7f0ffd31bb" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_fe9695b873d2b0150d1c595d59" ON "account_transfer_sender_total_value" ("sort_id") `)
        await db.query(`CREATE INDEX "IDX_d3ec036801b6de0cda02067d32" ON "account_transfer_sender_total_value" ("account_id") `)
        await db.query(`CREATE TABLE "account_transfer_receiver_total_count" ("id" character varying NOT NULL, "sort_id" integer NOT NULL, "account_id" text NOT NULL, "value" integer NOT NULL, "last_contribution_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_8c4fe4f4df0c2fe09f4add91dc1" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_26cc291229734473f185fccedf" ON "account_transfer_receiver_total_count" ("sort_id") `)
        await db.query(`CREATE INDEX "IDX_e74a02a84680b631c8d22b59b6" ON "account_transfer_receiver_total_count" ("account_id") `)
        await db.query(`CREATE TABLE "account_transfer_receiver_total_value" ("id" character varying NOT NULL, "sort_id" integer NOT NULL, "account_id" text NOT NULL, "value" numeric NOT NULL, "last_contribution_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_74b1219748b0947e2c01869330f" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_682663470b84a6286c6de9c3e5" ON "account_transfer_receiver_total_value" ("sort_id") `)
        await db.query(`CREATE INDEX "IDX_9ee1e5174195b11e00f87a14a4" ON "account_transfer_receiver_total_value" ("account_id") `)
        await db.query(`CREATE TABLE "account_remark_count" ("id" character varying NOT NULL, "sort_id" integer NOT NULL, "account_id" text NOT NULL, "value" integer NOT NULL, "last_contribution_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_84b4f048b6b0cfe0a91928e3c56" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_d3e23e3d8a8b04f4035a16a560" ON "account_remark_count" ("sort_id") `)
        await db.query(`CREATE INDEX "IDX_bba1087c1741367ec20b87dab5" ON "account_remark_count" ("account_id") `)
        await db.query(`CREATE TABLE "account_extrinsic_total_count" ("id" character varying NOT NULL, "sort_id" integer NOT NULL, "account_id" text NOT NULL, "value" integer NOT NULL, "last_contribution_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_2d4d99f8fd71e09782e04ce6383" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_416d2d64e00b98ee2ba2962118" ON "account_extrinsic_total_count" ("sort_id") `)
        await db.query(`CREATE INDEX "IDX_6557d340bb26e439dece6c76c0" ON "account_extrinsic_total_count" ("account_id") `)
        await db.query(`CREATE TABLE "account_extrinsic_success_total_count" ("id" character varying NOT NULL, "sort_id" integer NOT NULL, "account_id" text NOT NULL, "value" integer NOT NULL, "last_contribution_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_6347e36b6dab52598920f2bf6d5" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_5cfe3e12052b27c7865832e0a8" ON "account_extrinsic_success_total_count" ("sort_id") `)
        await db.query(`CREATE INDEX "IDX_48c48b892112e15d6ad43f4bb8" ON "account_extrinsic_success_total_count" ("account_id") `)
        await db.query(`CREATE TABLE "account_extrinsic_failed_total_count" ("id" character varying NOT NULL, "sort_id" integer NOT NULL, "account_id" text NOT NULL, "value" integer NOT NULL, "last_contribution_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_ad0f35e57a01949e40173e09fc0" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_6a175ae0ebd209ee54dfafbb7f" ON "account_extrinsic_failed_total_count" ("sort_id") `)
        await db.query(`CREATE INDEX "IDX_5bacf9fb89def1cac695d2a328" ON "account_extrinsic_failed_total_count" ("account_id") `)
        await db.query(`CREATE TABLE "account_transaction_fee_paid_total_value" ("id" character varying NOT NULL, "sort_id" integer NOT NULL, "account_id" text NOT NULL, "value" numeric NOT NULL, "last_contribution_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_575c98d771f13f9679578f5b9d7" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_ded05b774ba101284c1d922ddb" ON "account_transaction_fee_paid_total_value" ("sort_id") `)
        await db.query(`CREATE INDEX "IDX_2729d1fbb64f9f404e75370bd7" ON "account_transaction_fee_paid_total_value" ("account_id") `)
        await db.query(`CREATE TABLE "farmer_vote_total_count" ("id" character varying NOT NULL, "sort_id" integer NOT NULL, "account_id" text NOT NULL, "value" integer NOT NULL, "last_contribution_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_918f8e2d8e59a98268ff9b90091" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_b7e52d5097a84ca805624840d0" ON "farmer_vote_total_count" ("sort_id") `)
        await db.query(`CREATE INDEX "IDX_33008bf8f7d4294e77b2e81f1c" ON "farmer_vote_total_count" ("account_id") `)
        await db.query(`CREATE TABLE "farmer_vote_total_value" ("id" character varying NOT NULL, "sort_id" integer NOT NULL, "account_id" text NOT NULL, "value" numeric NOT NULL, "last_contribution_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_d0d5a314e74587ba1d363abada8" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_c4bba5ba51aadd9407a468daf0" ON "farmer_vote_total_value" ("sort_id") `)
        await db.query(`CREATE INDEX "IDX_173b011f52709d9f50ae8ac609" ON "farmer_vote_total_value" ("account_id") `)
        await db.query(`CREATE TABLE "farmer_block_total_count" ("id" character varying NOT NULL, "sort_id" integer NOT NULL, "account_id" text NOT NULL, "value" integer NOT NULL, "last_contribution_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_e95044f1288e5ed17d5afbb8d9d" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_34cb6e7b1b50df3b2bc286332d" ON "farmer_block_total_count" ("sort_id") `)
        await db.query(`CREATE INDEX "IDX_4e5250cb24a83863400811d6bb" ON "farmer_block_total_count" ("account_id") `)
        await db.query(`CREATE TABLE "farmer_block_total_value" ("id" character varying NOT NULL, "sort_id" integer NOT NULL, "account_id" text NOT NULL, "value" numeric NOT NULL, "last_contribution_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_9ec5ca1a42210d4b6b81b2c3767" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_618d6d1d0b329f88cf1ed69f71" ON "farmer_block_total_value" ("sort_id") `)
        await db.query(`CREATE INDEX "IDX_69960d7bdabaea0dacfef91c56" ON "farmer_block_total_value" ("account_id") `)
        await db.query(`CREATE TABLE "farmer_vote_and_block_total_count" ("id" character varying NOT NULL, "sort_id" integer NOT NULL, "account_id" text NOT NULL, "value" integer NOT NULL, "last_contribution_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_2ddfe1f33054ae3e6f0bc1d169b" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_901fc69471512224fd5a6fc024" ON "farmer_vote_and_block_total_count" ("sort_id") `)
        await db.query(`CREATE INDEX "IDX_0d435bf910f7649e41e0d910ad" ON "farmer_vote_and_block_total_count" ("account_id") `)
        await db.query(`CREATE TABLE "farmer_vote_and_block_total_value" ("id" character varying NOT NULL, "sort_id" integer NOT NULL, "account_id" text NOT NULL, "value" numeric NOT NULL, "last_contribution_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_c5e84d1cbe6d35a2be27dce2687" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_84e508c702007941d65e0f7a80" ON "farmer_vote_and_block_total_value" ("sort_id") `)
        await db.query(`CREATE INDEX "IDX_5fc8d3a9bdada634df0eacb15e" ON "farmer_vote_and_block_total_value" ("account_id") `)
        await db.query(`CREATE TABLE "operator_total_rewards_collected" ("id" character varying NOT NULL, "sort_id" integer NOT NULL, "operator_id" text NOT NULL, "value" numeric NOT NULL, "last_contribution_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_d508f86eb381e877ab636102aac" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_7a5de4103c3681ec194dcb7896" ON "operator_total_rewards_collected" ("sort_id") `)
        await db.query(`CREATE INDEX "IDX_44e627490bd490bb4f4b10c8aa" ON "operator_total_rewards_collected" ("operator_id") `)
        await db.query(`CREATE TABLE "operator_total_tax_collected" ("id" character varying NOT NULL, "sort_id" integer NOT NULL, "operator_id" text NOT NULL, "value" numeric NOT NULL, "last_contribution_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_ac699d330bc0ddf2c1abe2af16b" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_7b6d72c9586e83b5726e6c42dd" ON "operator_total_tax_collected" ("sort_id") `)
        await db.query(`CREATE INDEX "IDX_7568f60545cb2e5478075e8090" ON "operator_total_tax_collected" ("operator_id") `)
        await db.query(`CREATE TABLE "operator_bundle_total_count" ("id" character varying NOT NULL, "sort_id" integer NOT NULL, "domain_id" text NOT NULL, "operator_id" text NOT NULL, "value" integer NOT NULL, "last_contribution_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_8da0332f9c5fe77654da1ac45aa" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_9a4a1e0f6d14690b7843becb32" ON "operator_bundle_total_count" ("sort_id") `)
        await db.query(`CREATE INDEX "IDX_e4c866e5362798a2dcc9924259" ON "operator_bundle_total_count" ("domain_id") `)
        await db.query(`CREATE INDEX "IDX_2a82c276a1bd10785b3ad6b8a1" ON "operator_bundle_total_count" ("operator_id") `)
        await db.query(`CREATE TABLE "operator_deposits_total_count" ("id" character varying NOT NULL, "sort_id" integer NOT NULL, "operator_id" text NOT NULL, "value" integer NOT NULL, "last_contribution_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_23ecf13a9c3b7660aafd3482a6a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_be7ec85124ff60964f8b27450f" ON "operator_deposits_total_count" ("sort_id") `)
        await db.query(`CREATE INDEX "IDX_6993fd4035e7fca7e857dd7e2f" ON "operator_deposits_total_count" ("operator_id") `)
        await db.query(`CREATE TABLE "operator_deposits_total_value" ("id" character varying NOT NULL, "sort_id" integer NOT NULL, "operator_id" text NOT NULL, "value" numeric NOT NULL, "last_contribution_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_1aafd1c19361ddaf43b519bb9a2" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_2c69550cf3f0f89a00bac51502" ON "operator_deposits_total_value" ("sort_id") `)
        await db.query(`CREATE INDEX "IDX_6c77f594a022bf1528da83674d" ON "operator_deposits_total_value" ("operator_id") `)
        await db.query(`CREATE TABLE "operator_withdrawals_total_count" ("id" character varying NOT NULL, "sort_id" integer NOT NULL, "operator_id" text NOT NULL, "value" integer NOT NULL, "last_contribution_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_bb81061cc6ab3d65e5c831a3657" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_bc63ac482ec1ee29c47ab25963" ON "operator_withdrawals_total_count" ("sort_id") `)
        await db.query(`CREATE INDEX "IDX_d2ecff51a4d0aaa95cd09b6183" ON "operator_withdrawals_total_count" ("operator_id") `)
        await db.query(`CREATE TABLE "nominator_deposits_total_count" ("id" character varying NOT NULL, "sort_id" integer NOT NULL, "account_id" text NOT NULL, "value" integer NOT NULL, "last_contribution_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_4c569d7d27fe43e38f5588ba246" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_0c4f69aa51c6e678ca76e336fa" ON "nominator_deposits_total_count" ("sort_id") `)
        await db.query(`CREATE INDEX "IDX_38f2167567905d59b1d273ffd3" ON "nominator_deposits_total_count" ("account_id") `)
        await db.query(`CREATE TABLE "nominator_deposits_total_value" ("id" character varying NOT NULL, "sort_id" integer NOT NULL, "account_id" text NOT NULL, "value" numeric NOT NULL, "last_contribution_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_4a95edc83e860d25aaa76a03e68" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_2388ec11a039699755120415dc" ON "nominator_deposits_total_value" ("sort_id") `)
        await db.query(`CREATE INDEX "IDX_46faa628db4ca38988c257656c" ON "nominator_deposits_total_value" ("account_id") `)
        await db.query(`CREATE TABLE "nominator_withdrawals_total_count" ("id" character varying NOT NULL, "sort_id" integer NOT NULL, "account_id" text NOT NULL, "value" integer NOT NULL, "last_contribution_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, CONSTRAINT "PK_e983c41d64d1945553ae30a805d" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_a2c4cfd46fe54dc1b9faee6660" ON "nominator_withdrawals_total_count" ("sort_id") `)
        await db.query(`CREATE INDEX "IDX_a575e9d971232b73e9581e985e" ON "nominator_withdrawals_total_count" ("account_id") `)
    }

    async down(db) {
        await db.query(`DROP TABLE "account_transfer_sender_total_count"`)
        await db.query(`DROP INDEX "public"."IDX_5a702db2bccbcac5bd5746e383"`)
        await db.query(`DROP INDEX "public"."IDX_931cdd001f2cc8877feb2c80d3"`)
        await db.query(`DROP TABLE "account_transfer_sender_total_value"`)
        await db.query(`DROP INDEX "public"."IDX_fe9695b873d2b0150d1c595d59"`)
        await db.query(`DROP INDEX "public"."IDX_d3ec036801b6de0cda02067d32"`)
        await db.query(`DROP TABLE "account_transfer_receiver_total_count"`)
        await db.query(`DROP INDEX "public"."IDX_26cc291229734473f185fccedf"`)
        await db.query(`DROP INDEX "public"."IDX_e74a02a84680b631c8d22b59b6"`)
        await db.query(`DROP TABLE "account_transfer_receiver_total_value"`)
        await db.query(`DROP INDEX "public"."IDX_682663470b84a6286c6de9c3e5"`)
        await db.query(`DROP INDEX "public"."IDX_9ee1e5174195b11e00f87a14a4"`)
        await db.query(`DROP TABLE "account_remark_count"`)
        await db.query(`DROP INDEX "public"."IDX_d3e23e3d8a8b04f4035a16a560"`)
        await db.query(`DROP INDEX "public"."IDX_bba1087c1741367ec20b87dab5"`)
        await db.query(`DROP TABLE "account_extrinsic_total_count"`)
        await db.query(`DROP INDEX "public"."IDX_416d2d64e00b98ee2ba2962118"`)
        await db.query(`DROP INDEX "public"."IDX_6557d340bb26e439dece6c76c0"`)
        await db.query(`DROP TABLE "account_extrinsic_success_total_count"`)
        await db.query(`DROP INDEX "public"."IDX_5cfe3e12052b27c7865832e0a8"`)
        await db.query(`DROP INDEX "public"."IDX_48c48b892112e15d6ad43f4bb8"`)
        await db.query(`DROP TABLE "account_extrinsic_failed_total_count"`)
        await db.query(`DROP INDEX "public"."IDX_6a175ae0ebd209ee54dfafbb7f"`)
        await db.query(`DROP INDEX "public"."IDX_5bacf9fb89def1cac695d2a328"`)
        await db.query(`DROP TABLE "account_transaction_fee_paid_total_value"`)
        await db.query(`DROP INDEX "public"."IDX_ded05b774ba101284c1d922ddb"`)
        await db.query(`DROP INDEX "public"."IDX_2729d1fbb64f9f404e75370bd7"`)
        await db.query(`DROP TABLE "farmer_vote_total_count"`)
        await db.query(`DROP INDEX "public"."IDX_b7e52d5097a84ca805624840d0"`)
        await db.query(`DROP INDEX "public"."IDX_33008bf8f7d4294e77b2e81f1c"`)
        await db.query(`DROP TABLE "farmer_vote_total_value"`)
        await db.query(`DROP INDEX "public"."IDX_c4bba5ba51aadd9407a468daf0"`)
        await db.query(`DROP INDEX "public"."IDX_173b011f52709d9f50ae8ac609"`)
        await db.query(`DROP TABLE "farmer_block_total_count"`)
        await db.query(`DROP INDEX "public"."IDX_34cb6e7b1b50df3b2bc286332d"`)
        await db.query(`DROP INDEX "public"."IDX_4e5250cb24a83863400811d6bb"`)
        await db.query(`DROP TABLE "farmer_block_total_value"`)
        await db.query(`DROP INDEX "public"."IDX_618d6d1d0b329f88cf1ed69f71"`)
        await db.query(`DROP INDEX "public"."IDX_69960d7bdabaea0dacfef91c56"`)
        await db.query(`DROP TABLE "farmer_vote_and_block_total_count"`)
        await db.query(`DROP INDEX "public"."IDX_901fc69471512224fd5a6fc024"`)
        await db.query(`DROP INDEX "public"."IDX_0d435bf910f7649e41e0d910ad"`)
        await db.query(`DROP TABLE "farmer_vote_and_block_total_value"`)
        await db.query(`DROP INDEX "public"."IDX_84e508c702007941d65e0f7a80"`)
        await db.query(`DROP INDEX "public"."IDX_5fc8d3a9bdada634df0eacb15e"`)
        await db.query(`DROP TABLE "operator_total_rewards_collected"`)
        await db.query(`DROP INDEX "public"."IDX_7a5de4103c3681ec194dcb7896"`)
        await db.query(`DROP INDEX "public"."IDX_44e627490bd490bb4f4b10c8aa"`)
        await db.query(`DROP TABLE "operator_total_tax_collected"`)
        await db.query(`DROP INDEX "public"."IDX_7b6d72c9586e83b5726e6c42dd"`)
        await db.query(`DROP INDEX "public"."IDX_7568f60545cb2e5478075e8090"`)
        await db.query(`DROP TABLE "operator_bundle_total_count"`)
        await db.query(`DROP INDEX "public"."IDX_9a4a1e0f6d14690b7843becb32"`)
        await db.query(`DROP INDEX "public"."IDX_e4c866e5362798a2dcc9924259"`)
        await db.query(`DROP INDEX "public"."IDX_2a82c276a1bd10785b3ad6b8a1"`)
        await db.query(`DROP TABLE "operator_deposits_total_count"`)
        await db.query(`DROP INDEX "public"."IDX_be7ec85124ff60964f8b27450f"`)
        await db.query(`DROP INDEX "public"."IDX_6993fd4035e7fca7e857dd7e2f"`)
        await db.query(`DROP TABLE "operator_deposits_total_value"`)
        await db.query(`DROP INDEX "public"."IDX_2c69550cf3f0f89a00bac51502"`)
        await db.query(`DROP INDEX "public"."IDX_6c77f594a022bf1528da83674d"`)
        await db.query(`DROP TABLE "operator_withdrawals_total_count"`)
        await db.query(`DROP INDEX "public"."IDX_bc63ac482ec1ee29c47ab25963"`)
        await db.query(`DROP INDEX "public"."IDX_d2ecff51a4d0aaa95cd09b6183"`)
        await db.query(`DROP TABLE "nominator_deposits_total_count"`)
        await db.query(`DROP INDEX "public"."IDX_0c4f69aa51c6e678ca76e336fa"`)
        await db.query(`DROP INDEX "public"."IDX_38f2167567905d59b1d273ffd3"`)
        await db.query(`DROP TABLE "nominator_deposits_total_value"`)
        await db.query(`DROP INDEX "public"."IDX_2388ec11a039699755120415dc"`)
        await db.query(`DROP INDEX "public"."IDX_46faa628db4ca38988c257656c"`)
        await db.query(`DROP TABLE "nominator_withdrawals_total_count"`)
        await db.query(`DROP INDEX "public"."IDX_a2c4cfd46fe54dc1b9faee6660"`)
        await db.query(`DROP INDEX "public"."IDX_a575e9d971232b73e9581e985e"`)
    }
}
