query EventsAggregate($where: consensus_events_bool_exp) @cached(ttl: 60000) {
  consensus_events_aggregate(where: $where) {
    aggregate {
      count
    }
  }
}

query EventsModules {
  consensus_event_modules {
    section
    method
  }
}

query EventById($eventId: String!) {
  consensus_events(where: { id: { _eq: $eventId } }) {
    id
    extrinsic_id
    block_height
    section
    module
    timestamp
    args
  }
}
