query EventsModules {
  consensus_event_modules {
    section
    method
  }
}

query EventsAggregate($where: consensus_events_bool_exp) @cached(ttl: 60000) {
  consensus_events_aggregate(where: $where) {
    aggregate {
      count
    }
  }
}

query SearchEventsByBlockHash($search: String!, $limit: Int!) {
  consensus_search_events_by_block_hash(args: { search: $search }, limit: $limit) {
    id
    sortId: sort_id
    blockHeight: block_height
    extrinsicId: extrinsic_id
    module
    indexInBlock: index_in_block
    timestamp
    blockHash: block_hash
  }
  consensus_search_events_by_block_hash_aggregate(args: { search: $search }) {
    aggregate {
      count
    }
  }
}

query EventById($eventId: String!) {
  consensus_events(where: { id: { _eq: $eventId } }) {
    id
    extrinsic_id
    block_height
    section
    module
    timestamp
    args
  }
}
