import { test, expect } from '@playwright/test'

test('data show', async ({ page }) => {
  await page.goto('/#/blocks/1229129')

  await expect(page.getByRole('heading', { name: 'Block #1229129' })).toBeVisible()
  await expect(page.getByText('Best Block')).toBeVisible()
  await expect(page.getByText('Timestamp')).toBeVisible()
  await expect(page.getByText('Block Time')).toBeVisible()
  await page
    .getByRole('listitem')
    .filter({ hasText: 'Hash0xf2a1c6fff84a54e22dd674077fdc57778c6ac7da4085896dd4b3c664d65ba76e' })
    .getByRole('paragraph')
    .click()
  await expect(await page.getByText('Parent Hash')).toBeVisible()
  await expect(page.getByText('Extrinsics Root')).toBeVisible()
  await expect(page.getByText('Spec Version')).toBeVisible()
  await expect(page.getByText('01 Dec 2022 | 14:56:42(-04:00)')).toBeVisible()

  await expect(page.getByText('subspace@4')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Extrinsics' })).toBeVisible()
  await expect(page.getByText('Extrinsic Id')).toBeVisible()
  await expect(page.getByText('Block hash')).toBeVisible()
  await expect(page.getByText('Action')).toBeVisible()
  await expect(page.getByRole('cell', { name: 'Time' }).getByText('Time')).toBeVisible()
  await expect(page.getByText('Status')).toBeVisible()
  await page.getByRole('button', { name: 'Events' }).click()
  await expect(page.getByText('Event Id')).toBeVisible()
  await expect(page.getByText('Extrinsic Id')).toBeVisible()
  await expect(page.getByText('Action')).toBeVisible()
  await expect(page.getByText('Type')).toBeVisible()
  await page.getByRole('button', { name: 'Logs' }).click()
  await expect(page.getByText('Log Index')).toBeVisible()
  await expect(page.getByRole('cell', { name: 'Block' }).getByText('Block')).toBeVisible()
  await expect(page.getByText('Type')).toBeVisible()
})
