query AccountsTopLeaderboard($first: Int!) {
  farmers: consensus_rewards(
    order_by: { amount: desc }
    limit: $first
    where: {
      _or: [
        { reward_type: { _eq: "Rewards.VoteReward" } }
        { reward_type: { _eq: "Rewards.BlockReward" } }
      ]
    }
  ) {
    id
  }
  # TODO: change this for operators
  operators: consensus_rewards(
    order_by: { amount: desc }
    limit: $first
    where: {
      _or: [
        { reward_type: { _eq: "Rewards.VoteReward" } }
        { reward_type: { _eq: "Rewards.BlockReward" } }
      ]
    }
  ) {
    id
  }
  # TODO: change this for nominators
  nominators: consensus_rewards(
    order_by: { amount: desc }
    limit: $first
    where: {
      _or: [
        { reward_type: { _eq: "Rewards.VoteReward" } }
        { reward_type: { _eq: "Rewards.BlockReward" } }
      ]
    }
  ) {
    id
  }
}

query PendingTransaction($subspaceAccount: String, $extrinsics: [String!]) {
  consensus_accounts(where: { id: { _eq: $subspaceAccount } }) {
    id
    extrinsics(where: { hash: { _in: $extrinsics } }) {
      hash
      success
      timestamp
      name
      events(limit: 1, order_by: { id: desc }) {
        name
      }
      block {
        hash
        height
        id
      }
    }
  }
}

query ExtrinsicsSummary($first: Int!, $subspaceAccount: String) {
  consensus_extrinsics_aggregate(where: { signer: { _eq: $subspaceAccount } }) {
    aggregate {
      count
    }
  }
  extrinsics: consensus_extrinsics(
    order_by: { id: desc }
    limit: $first
    where: { signer: { _eq: $subspaceAccount } }
  ) {
    id
    hash
    success
    timestamp
    block_height
    name
  }
}

query CheckRole($subspaceAccount: String!) {
  isFarmer: consensus_rewards(
    where: {
      _or: [
        { reward_type: { _eq: "rewards.VoteReward" } }
        { reward_type: { _eq: "rewards.BlockReward" } }
      ]
      account_id: { _eq: $subspaceAccount }
    }
    limit: 1
  ) {
    account {
      id
    }
  }
  isOperator: staking_operators(
    where: { account_id: { _eq: $subspaceAccount }, status: { _eq: "ACTIVE" } }
    limit: 1
    order_by: { id: asc }
  ) {
    id
  }
  isNominator: staking_accounts(
    where: { id: { _eq: $subspaceAccount }, current_total_stake: { _gt: 0 } }
    limit: 1
    order_by: { id: asc }
  ) {
    id
  }
  isTalismanFarmer: consensus_rewards(
    where: {
      _or: [
        { reward_type: { _eq: "rewards.VoteReward" } }
        { reward_type: { _eq: "rewards.BlockReward" } }
      ]
      account_id: { _eq: $subspaceAccount }
    }
    limit: 1
  ) {
    account {
      id
    }
  }
}

query StakingSummary($first: Int!, $subspaceAccount: String) {
  staking_operators(
    order_by: { id: asc }
    limit: $first
    where: { account_id: { _eq: $subspaceAccount } }
  ) {
    id
    account_id
    domain_id
    current_total_stake
    current_total_shares
  }
  staking_operators_aggregate(
    order_by: { id: asc }
    where: { account_id: { _eq: $subspaceAccount } }
  ) {
    aggregate {
      count
    }
  }
  staking_nominators(
    order_by: { id: asc }
    limit: $first
    where: { account_id: { _eq: $subspaceAccount } }
  ) {
    id
    known_shares
    known_storage_fee_deposit
    account {
      id
    }
    operator {
      id
      account_id
      domain_id
      current_total_stake
      current_total_shares
      current_share_price
    }
    deposits {
      estimated_shares
    }
    withdrawals {
      unlocked_amount
      unlocked_storage_fee
      total_amount
    }
  }
  staking_nominators_aggregate(
    order_by: { id: asc }
    where: { account_id: { _eq: $subspaceAccount } }
  ) {
    aggregate {
      count
    }
  }
}
