query PendingTransaction($subspaceAccount: String, $extrinsics: [String!]) {
  consensus_accounts(where: { id: { _eq: $subspaceAccount } }) {
    id
    extrinsics(where: { hash: { _in: $extrinsics } }) {
      hash
      success
      timestamp
      name
      events(limit: 1, order_by: { id: desc }) {
        name
      }
      block {
        hash
        height
        id
      }
    }
  }
}

query ExtrinsicsSummary($first: Int!, $subspaceAccount: String) {
  consensus_extrinsics_aggregate(where: { signer: { _eq: $subspaceAccount } }) {
    aggregate {
      count
    }
  }
  extrinsics: consensus_extrinsics(
    order_by: { sort_id: desc }
    limit: $first
    where: { signer: { _eq: $subspaceAccount } }
  ) {
    id
    hash
    success
    timestamp
    block_height
    name
  }
}

query CheckRole($subspaceAccount: String!) {
  isFarmer: consensus_rewards(
    where: {
      _or: [
        { reward_type: { _eq: "rewards.VoteReward" } }
        { reward_type: { _eq: "rewards.BlockReward" } }
      ]
      account_id: { _eq: $subspaceAccount }
    }
    limit: 1
  ) {
    account {
      id
    }
  }
  isOperator: staking_operators(
    where: { account_id: { _eq: $subspaceAccount }, status: { _eq: "ACTIVE" } }
    limit: 1
    order_by: { id: asc }
  ) {
    id
  }
  isNominator: staking_accounts(
    where: { id: { _eq: $subspaceAccount }, current_total_stake: { _gt: 0 } }
    limit: 1
    order_by: { id: asc }
  ) {
    id
  }
  isTalismanFarmer: consensus_rewards(
    where: {
      _or: [
        { reward_type: { _eq: "rewards.VoteReward" } }
        { reward_type: { _eq: "rewards.BlockReward" } }
      ]
      account_id: { _eq: $subspaceAccount }
      _and: [
        { timestamp: { _gte: "2025-05-07T00:00:00.000" } }
        { timestamp: { _lte: "2025-06-05T00:00:00.000" } }
      ]
    }
    limit: 1
  ) {
    account {
      id
    }
  }
}
