export * as system from './system/calls'
export * as timestamp from './timestamp/calls'
export * as subspace from './subspace/calls'
export * as balances from './balances/calls'
export * as utility from './utility/calls'
export * as domains from './domains/calls'
export * as messenger from './messenger/calls'
export * as rewards from './rewards/calls'
