query Blocks(
  $limit: Int!
  $offset: Int
  $orderBy: [consensus_blocks_order_by!]!
  $where: consensus_blocks_bool_exp
) {
  consensus_blocks_aggregate(where: $where) {
    aggregate {
      count
    }
  }
  consensus_blocks(order_by: $orderBy, limit: $limit, offset: $offset, where: $where) {
    id
    height
    hash
    timestamp
    parentHash: parent_hash
    specId: spec_id
    stateRoot: state_root
    extrinsicsRoot: extrinsics_root
    spacePledged: space_pledged
    blockchainSize: blockchain_size
    extrinsicsCount: extrinsics_count
    eventsCount: events_count
    authorId: author_id
  }
}

query BlockById($blockId: String!, $blockHash: String!) {
  consensus_blocks(where: { _or: [{ id: { _eq: $blockId } }, { hash: { _eq: $blockHash } }] }) {
    id
    height
    hash
    state_root
    timestamp
    extrinsics_root
    spec_id
    parent_hash
    extrinsics_count
    events_count
    logs_count
    author_id
  }
}

query ExtrinsicsByBlockId(
  $blockHeight: numeric!
  $limit: Int!
  $offset: Int
  $orderBy: [consensus_extrinsics_order_by!]
) {
  consensus_extrinsics(
    order_by: $orderBy
    limit: $limit
    offset: $offset
    where: { block_height: { _eq: $blockHeight } }
  ) {
    id
    hash
    section
    module
    success
  }
}

query EventsByBlockId(
  $blockHeight: numeric!
  $limit: Int!
  $offset: Int
  $orderBy: [consensus_events_order_by!]
) {
  consensus_events(
    order_by: $orderBy
    limit: $limit
    offset: $offset
    where: { block_height: { _eq: $blockHeight } }
  ) {
    id
    section
    module
    phase
    extrinsic_id
  }
}

query LogsByBlockId(
  $blockHeight: numeric!
  $limit: Int!
  $offset: Int
  $orderBy: [consensus_logs_order_by!]
) {
  consensus_logs(
    order_by: $orderBy
    limit: $limit
    offset: $offset
    where: { block_height: { _eq: $blockHeight } }
  ) {
    id
    kind
    block_height
  }
}
