query ExtrinsicsCountAndModules($where: consensus_extrinsics_bool_exp) {
  consensus_extrinsics_aggregate(where: $where) {
    aggregate {
      count
    }
  }
  consensus_extrinsic_modules {
    section
    method
  }
}

query ExtrinsicsById($extrinsicId: String!) {
  consensus_extrinsics(
    where: { _or: [{ id: { _eq: $extrinsicId } }, { hash: { _eq: $extrinsicId } }] }
  ) {
    id
    hash
    block_height
    section
    module
    timestamp
    success
    signature
    signer
    args
    events_count
  }
}

query EventsByExtrinsicId(
  $extrinsicId: String!
  $limit: Int!
  $offset: Int
  $orderBy: [consensus_events_order_by!]
) {
  consensus_events(
    order_by: $orderBy
    limit: $limit
    offset: $offset
    where: { extrinsic_id: { _eq: $extrinsicId } }
  ) {
    id
    section
    module
    phase
    extrinsic_id
  }
}
