query ExtrinsicsAggregate($where: consensus_extrinsics_bool_exp) @cached(ttl: 60000) {
  consensus_extrinsics_aggregate(where: $where) {
    aggregate {
      count
    }
  }
}

query ExtrinsicsModules {
  consensus_extrinsic_modules {
    section
    method
  }
}

query ExtrinsicsByBlockHash($limit: Int!, $offset: Int, $where: consensus_blocks_bool_exp) {
  consensus_blocks(limit: $limit, offset: $offset, where: $where) {
    id
    authorId: author_id
    extrinsics(order_by: { index_in_block: asc }) {
      id
      hash
      blockHeight: block_height
      indexInBlock: index_in_block
      section
      success
      timestamp
      module
      blockHash: block_hash
    }
  }
}

query ExtrinsicsById($extrinsicId: String!) {
  consensus_extrinsics(where: { id: { _eq: $extrinsicId } }) {
    id
    hash
    block_height
    section
    module
    timestamp
    success
    signature
    signer
    args
    events_count
  }
}

query EventsByExtrinsicId(
  $extrinsicId: String!
  $limit: Int!
  $offset: Int
  $orderBy: [consensus_events_order_by!]
) {
  consensus_events(limit: $limit, offset: $offset, where: { extrinsic_id: { _eq: $extrinsicId } }) {
    id
    section
    module
    phase
    extrinsic_id
  }
}
