export enum OperatorStatus {
  PENDING_NEXT_EPOCH = 'PENDING_NEXT_EPOCH',
  ACTIVE = 'ACTIVE',
  DEREGISTERED = 'DEREGISTERED',
  NOMINATORS_UNLOCKED = 'NOMINATORS_UNLOCKED',
  SLASHED = 'SLASHED',
}

export enum NominatorStatus {
  PENDING_NEXT_EPOCH = 'PENDING_NEXT_EPOCH',
  ACTIVE = 'ACTIVE',
}

export enum DepositStatus {
  PENDING_NEXT_EPOCH = 'PENDING_NEXT_EPOCH',
  ACTIVE = 'ACTIVE',
}

export enum WithdrawalStatus {
  PENDING_NEXT_EPOCH = 'PENDING_NEXT_EPOCH',
  PENDING_CHALLENGE_PERIOD = 'PENDING_CHALLENGE_PERIOD',
  PENDING_UNLOCK_FUNDS = 'PENDING_UNLOCK_FUNDS',
  FUNDS_UNLOCKED = 'FUNDS_UNLOCKED',
}
