name: Web Vitals CI

on:
  push:
    branches: [main]
    paths: ["explorer/**"]
  pull_request:
    branches: [main]
    paths: ["explorer/**"]

jobs:
  web-vitals:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: explorer
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: explorer/yarn.lock

      - run: corepack enable

      - run: yarn install --frozen-lockfile

      - name: Deploy to Vercel
        id: vercel-deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
        env:
          AUTO_DRIVE_API_KEY: ${{ secrets.AUTO_DRIVE_API_KEY }}
          AUTO_EVM_RPC_URL: ${{ secrets.AUTO_EVM_RPC_URL }}
          USER_SESSION_CONTRACT_ADDRESS: ${{ secrets.USER_SESSION_CONTRACT_ADDRESS }}
          USER_SESSION_PRIVATE_KEY: ${{ secrets.USER_SESSION_PRIVATE_KEY }}
          NEXT_PUBLIC_MAINNET_INDEXERS: ${{ secrets.NEXT_PUBLIC_MAINNET_INDEXERS }}
          NEXT_PUBLIC_TAURUS_INDEXERS: ${{ secrets.NEXT_PUBLIC_TAURUS_INDEXERS }}

      - name: Wait for deployment to be ready
        run: sleep 30

      - name: Create artifacts directory
        run: mkdir -p ${{ github.workspace }}/tmp/artifacts

      - name: Run Lighthouse Check
        id: lighthouseCheck
        uses: foo-software/lighthouse-check-action@master
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          author: ${{ github.actor }}
          branch: ${{ github.ref }}
          prCommentEnabled: true
          outputDirectory: ${{ github.workspace }}/tmp/artifacts
          emulatedFormFactor: "all"
          urls: ${{ steps.vercel-deploy.outputs.preview-url }}
          sha: ${{ github.sha }}

      - name: Handle Lighthouse Check results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minAccessibilityScore: "70"
          minBestPracticesScore: "50"
          minPerformanceScore: "75"
          minProgressiveWebAppScore: "10"
          minSeoScore: "50"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-reports
          path: ${{ github.workspace }}/tmp/artifacts

      - name: Comment PR with preview URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **Preview Deployment**: ${{ steps.vercel-deploy.outputs.preview-url }}
              
              📊 **Web Vitals Report**: Check the Lighthouse results above for performance metrics.`
            })
