name: Web Vitals CI with Unlighthouse

on:
  push:
    branches: [main]
    paths: ["explorer/**"]
  pull_request:
    branches: [main]
    paths: ["explorer/**"]
  workflow_dispatch:

jobs:
  web-vitals:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: explorer
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: explorer/yarn.lock

      - run: corepack enable

      - run: yarn install --frozen-lockfile

      - name: Deploy to Vercel
        id: vercel-deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
        env:
          AUTO_DRIVE_API_KEY: ${{ secrets.AUTO_DRIVE_API_KEY }}
          AUTO_EVM_RPC_URL: ${{ secrets.AUTO_EVM_RPC_URL }}
          USER_SESSION_CONTRACT_ADDRESS: ${{ secrets.USER_SESSION_CONTRACT_ADDRESS }}
          USER_SESSION_PRIVATE_KEY: ${{ secrets.USER_SESSION_PRIVATE_KEY }}
          NEXT_PUBLIC_MAINNET_INDEXERS: ${{ secrets.NEXT_PUBLIC_MAINNET_INDEXERS }}
          NEXT_PUBLIC_TAURUS_INDEXERS: ${{ secrets.NEXT_PUBLIC_TAURUS_INDEXERS }}

      - name: Wait for deployment to be ready
        run: sleep 30

      - name: Install Unlighthouse Dependencies
        run: |
          cd ${{ github.workspace }}
          npm add @unlighthouse/cli puppeteer

      - name: Create artifacts directory
        run: mkdir -p ${{ github.workspace }}/tmp/artifacts

      - name: Run Unlighthouse CI with budget assertions and static build
        run: |
          cd ${{ github.workspace }}
          # Scan only the home page
          npx unlighthouse-ci --site ${{ steps.vercel-deploy.outputs.preview-url }} --budget 75 --build-static --debug --urls "/"

          # Alternative: Scan all discovered routes (commented out)
          # npx unlighthouse-ci --site ${{ steps.vercel-deploy.outputs.preview-url }} --budget 75 --build-static --debug
        continue-on-error: true

      - name: Copy Unlighthouse reports to artifacts
        run: |
          if [ -d "${{ github.workspace }}/.lighthouse" ]; then
            cp -r ${{ github.workspace }}/.lighthouse/* ${{ github.workspace }}/tmp/artifacts/
          fi

      - name: Deploy Unlighthouse report to Vercel
        id: vercel-report-deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_REPORT_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          working-directory: ${{ github.workspace }}/.lighthouse/client
        continue-on-error: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unlighthouse-reports
          path: ${{ github.workspace }}/tmp/artifacts

      - name: Comment PR with preview URL and report
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            let body = `🚀 **Preview Deployment**: ${{ steps.vercel-deploy.outputs.preview-url }}

            📊 **Web Vitals Report**: Unlighthouse analysis completed with budget threshold of 75.`;

            if ('${{ steps.vercel-report-deploy.outputs.preview-url }}') {
              body += `\n📈 **Unlighthouse Report**: ${{ steps.vercel-report-deploy.outputs.preview-url }}`;
            }

            body += `\n\n💡 **Budget Assertions**: Performance, Accessibility, Best Practices, and SEO scores must be ≥75 to pass.`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
