name: Web Vitals CI

on:
  push:
    branches: [main]
    paths: ["explorer/**"]
  pull_request:
    branches: [main]
    paths: ["explorer/**"]

jobs:
  web-vitals:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: explorer
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: explorer/yarn.lock

      - run: corepack enable

      - run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
        env:
          AUTO_DRIVE_API_KEY: ${{ secrets.AUTO_DRIVE_API_KEY }}
          AUTO_EVM_RPC_URL: ${{ secrets.AUTO_EVM_RPC_URL }}
          USER_SESSION_CONTRACT_ADDRESS: ${{ secrets.USER_SESSION_CONTRACT_ADDRESS }}
          USER_SESSION_PRIVATE_KEY: ${{ secrets.USER_SESSION_PRIVATE_KEY }}
          NEXT_PUBLIC_MAINNET_INDEXERS: ${{ secrets.NEXT_PUBLIC_MAINNET_INDEXERS }}
          NEXT_PUBLIC_TAURUS_INDEXERS: ${{ secrets.NEXT_PUBLIC_TAURUS_INDEXERS }}

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: "explorer/lighthouserc.js"
          uploadArtifacts: true
          temporaryPublicStorage: true
        env:
          AUTO_DRIVE_API_KEY: ${{ secrets.AUTO_DRIVE_API_KEY }}
          AUTO_EVM_RPC_URL: ${{ secrets.AUTO_EVM_RPC_URL }}
          USER_SESSION_CONTRACT_ADDRESS: ${{ secrets.USER_SESSION_CONTRACT_ADDRESS }}
          USER_SESSION_PRIVATE_KEY: ${{ secrets.USER_SESSION_PRIVATE_KEY }}
          NEXT_PUBLIC_MAINNET_INDEXERS: ${{ secrets.NEXT_PUBLIC_MAINNET_INDEXERS }}
          NEXT_PUBLIC_TAURUS_INDEXERS: ${{ secrets.NEXT_PUBLIC_TAURUS_INDEXERS }}
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-reports
          path: explorer/.lighthouseci
